[package]
name = "leapfrog"
version = "0.1.0"
authors = ["saethlin <kimockb@gmail.com>"]

[dependencies]
rand = "*"

[profile.dev]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
