[package]
name = "leapfrog"
version = "0.1.0"
authors = ["saethlin <kimockb@gmail.com>"]

[dependencies]
rand = "*"
rust-ini = "*"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
